services:
  consul-server:
    image: docker.io/hashicorp/consul:latest
    container_name: consul-server
    # Command to run Consul in development mode with UI and accessible client interface
    command: agent -dev -client=0.0.0.0 -bind=0.0.0.0 -ui
    ports:
      - "8500:8500" # HTTP API and UI
      - "8600:8600/udp" # DNS interface (UDP)
    volumes:
      # Optional: Persist Consul's data if you stop/start the container.
      # Remove this line and the 'volumes:' section at the bottom if you don't need persistence for development.
      - ./consul_data:/consul/data
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5

  two-models-service:
    build: ./services/two-models
    ports:
      - "9000:9000"
    volumes:
      - ./services/two-models:/app
    environment:
      SERVICE_NAME: "two-models"
      SERVICE_HOST: "two-models-service"
      SERVICE_PORT: 9000
      CONSUL_HOST: "consul-server"
      CONSUL_PORT: 8500
    depends_on:
      - consul-server

  iris-service:
    build: ./services/iris
    ports:
      - "9001:9001"
    volumes:
     - ./services/iris:/app
    environment:
      SERVICE_NAME: "iris"
      SERVICE_HOST: "iris-service"
      SERVICE_PORT: 9001
      CONSUL_HOST: "consul-server"
      CONSUL_PORT: 8500
    depends_on:
      - consul-server

  nginx-reverse-proxy:
    build: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - ./nginx/nginx.conf.ctmpl:/etc/consul-template/templates/nginx.conf.ctmpl
    environment:
      # Tell Consul-Template where to find Consul
      CONSUL_HOST: consul-server
      CONSUL_PORT: 8500
      NGINX_PORT: ${GATEWAY_PORT}
    depends_on:
      consul-server:
        condition: service_healthy

  backend:
    build: be
    ports:
      - "${BACKEND_ENTRY_PORT}:${BACKEND_ENTRY_PORT}"
    volumes:
      - ./be:/app
    environment:
      FRONTEND_HOST: ${FRONTEND_HOSTNAME}
      FRONTEND_PORT: ${FRONTEND_PORT}
      THIS_HOST: backend
      THIS_PORT: ${BACKEND_ENTRY_PORT}
      GATEWAY_HOST: nginx-reverse-proxy
      GATEWAY_PORT: ${GATEWAY_PORT}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

  frontend:
    build:
      context: fe
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./fe:/app
    environment:
      VITE_HOST: frontend
      VITE_PORT: ${FRONTEND_PORT}
      VITE_API_HOST: ${BACKEND_ENTRY_HOSTNAME}
      VITE_API_PORT: ${BACKEND_ENTRY_PORT}

volumes:
  consul_data:
    driver: local
